name: wallpaper_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  async_wallpaper: ^2.0.1
  awesome_snackbar_content: ^0.1.0
  flutter_neumorphic: ^3.2.0
  bloc: ^8.1.0
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  bubble_loader: ^1.0.2
  flutter_svg: ^1.1.6
  custom_refresh_indicator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Handlee-Regular
      fonts:
        - asset: assets/Handlee-Regular.ttf
